export const POZO_FIND_ALL = 'POZO_FIND_ALL';
export const POZO_FIND_ALL_SIMPLE = 'POZO_FIND_ALL_SIMPLE';
export const POZO_FIND_ALL_SIMPLE_BY_IDS = 'POZO_FIND_ALL_SIMPLE_BY_IDS';
export const POZO_FIND_BY_ID = 'POZO_FIND_BY_ID';
export const POZO_PAGINATED_SEARCH = 'POZO_PAGINATED_SEARCH';
